# Generated by Django 2.2.3 on 2020-01-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0002_auto_20200115_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedidos',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador de Restaurante'), (2, 'Usuario')], default=2),
        ),
        migrations.CreateModel(
            name='DescripcionPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('preciototal', models.IntegerField()),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plato', to='Dippitimer.MenuItem')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numpedido', to='Dippitimer.Pedido')),
            ],
        ),
    ]
