# Generated by Django 2.2.3 on 2020-01-16 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0003_auto_20200116_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='descripcionpedido',
            name='menuItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Dippitimer.MenuItem'),
        ),
        migrations.AlterField(
            model_name='descripcionpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descpedido', to='Dippitimer.Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpedidos', to='Dippitimer.Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueño', to=settings.AUTH_USER_MODEL),
        ),
    ]
