# Generated by Django 2.2.3 on 2020-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0004_auto_20200116_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='Descrpicion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
