# Generated by Django 2.2.3 on 2020-01-22 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0005_menuitem_descrpicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueno', to=settings.AUTH_USER_MODEL),
        ),
    ]
