# Generated by Django 2.2.3 on 2020-01-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0007_auto_20200128_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
