# Generated by Django 2.2.3 on 2020-01-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0008_auto_20200130_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Nombre',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
