# Generated by Django 2.2.3 on 2020-02-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0012_listaingredientes_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaingredientes',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precioaprox',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
