# Generated by Django 2.2.3 on 2020-02-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0013_auto_20200203_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaingredientes',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precioaprox',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
    ]
