# Generated by Django 2.2.3 on 2020-02-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0016_auto_20200204_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
