# Generated by Django 2.2.3 on 2020-02-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0017_ingrediente_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precioayer',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='plato',
            name='preciohoy',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
    ]
