# Generated by Django 2.2.3 on 2020-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0022_auto_20200204_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='tasa',
        ),
        migrations.AddField(
            model_name='plato',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
    ]
