# Generated by Django 2.2.3 on 2020-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0024_auto_20200204_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
