# Generated by Django 2.2.3 on 2020-02-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0025_ingrediente_tasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='tasa',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='tasa',
        ),
    ]
