# Generated by Django 2.2.3 on 2020-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0026_auto_20200204_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaingredientes',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
    ]
