# Generated by Django 2.2.3 on 2020-02-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0027_listaingredientes_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaingredientes',
            name='descuento',
        ),
        migrations.AddField(
            model_name='plato',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
    ]
