# Generated by Django 2.2.3 on 2020-02-05 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0028_auto_20200204_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precioayer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='plato',
            name='preciohoy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
