# Generated by Django 2.2.3 on 2020-02-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0029_auto_20200205_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
