# Generated by Django 2.2.3 on 2020-05-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dippitimer', '0030_auto_20200205_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='preparacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=56),
        ),
        migrations.AddField(
            model_name='plato',
            name='tags',
            field=models.ManyToManyField(to='Dippitimer.Tags'),
        ),
    ]
